# Generated by Django 3.2 on 2025-04-01 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20250401_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2025), django.core.validators.MinValueValidator(-3000)], verbose_name='Год создания'),
        ),
    ]
