# Generated by Django 3.2 on 2025-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20250406_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', through='reviews.Title_Genre', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
