# Generated by Django 3.2 on 2025-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Идентификатор категории для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Slug категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Идентификатор жанра для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Slug жанра'),
        ),
    ]
